### ISSUE TITLE
I'm trying to use this package to add my branch name before commit message

### ISSUE THREAD

**Issue by leandroluk** [ljpengelen/prefix-commit-message#12]
Hi, I'm searching by a solution to add my branch name before every commit. I have a automation in jira to check some content in branch name and dispatch some trigger. Normally my branch names is like `{{task_type}}/{{jira_identifier}} - {{commit_message}}`, see examples: 

- "FT/WEB-123 - feat: test 123"
- "BUG/API-123 - chore: something"
- "HT/WEB-123 - test: function example"

Can you help me with the correct command to use this package to add branch name before commit message?

**Comment by ljpengelen** [comment]
Hi Leandro,

Sorry for the slow response. I read your question last week and then completely forgot about it.

I'm not sure I understand the question. Is it the case that your branches are named something like "FT/WEB-123" and that you want your commit message to be prefixed with "FT/WEB-123 - " automatically, such that you only have to write the "feat: test 123" part manually?

At the moment, this package doesn't support this use case. I could add support for it, but I'll postpone doing that until it's clear that this is indeed what you want to achieve.
